export const MESSAGE_CODE = {
    NOT_FOUND: "NOT_FOUND",
    UNAUTHORIZED: "UNAUTHORIZED",
    FORBIDDEN: "FORBIDDEN",
    BAD_REQUEST: "BAD REQUEST",
    CREATED: "CREATED",
    SUCCESS: "SUCCESS",
    INTERNAL_SERVER_ERROR: "ERROR",
    CATEGORY_RELATED_PRODUCTS: "CATEGORY_RELATED_PRODUCTS"
}